@host = https://localhost:7121

POST  {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Nick",
    "lastName": "Nuhu",
    "Email": "nickflinks@gmail.com",
    "Password": "Nicklas@9",
    "ConfirmPassword": "Nicklas@9"
}
